pipeline {
  agent {
    label 'main'
  }

  environment {
    GITHUB_PAT = credentials('gha-jenkins-handshake-pat-token')
  }

  stages {

    stage('Deploy to TESTING') {

        steps {

            def URL = 'https://api.github.com/repos/chalu/gha-jenkins-handshake/actions/workflows/12145487/dispatches'
            sh 'curl -v POST -H \'Accept: application/vnd.github.v3+json\' -H \'Authorization: token $GITHUB_PAT\' $URL -d \'{"ref":"develop", "inputs": { "environment":"testing"}}\''

            //  workflow-dispatch
            // httpRequest (
            //     httpMode: 'POST',
            //     requestBody: '''{
            //       "ref": "develop",
            //       "inputs": {
            //         "environment": "testing"
            //       }
            //     }''',
            //     consoleLogResponseBody: true,
            //     validResponseCodes: '200, 401',
            //     url: 'https://api.github.com/repos/chalu/gha-jenkins-handshake/actions/workflows/12145487/dispatches',
            //     customHeaders: [[name: 'Accept', value: 'application/vnd.github.v3+json'], [name: 'Authorization', value: 'token $GITHUB_PAT', maskValue: false]]
            // )

            // repository-dispatch
            // httpRequest (
            //     httpMode: 'POST',
            //     requestBody: '''{
            //       "event_type": "newman",
            //       "client_payload": {
            //         "environment": "testing"
            //       }
            //     }''',
            //     consoleLogResponseBody: true,
            //     validResponseCodes: '200, 401',
            //     url: 'https://api.github.com/repos/chalu/gha-jenkins-handshake/dispatches',
            //     customHeaders: [[name: 'Accept', value: 'application/vnd.github.everest-preview+json'], [name: 'Authorization', value: 'Bearer 5648684569457694657', maskValue: false]]
            // )
        }
    }
    
  }

  post {
    always {
      cleanWs()
    }
  }
}
