name: Test & Deploy Feature

on:
  push:
    branches:
      - "ft-*"

jobs:
  test: 
    runs-on: ubuntu-18.04
    name: 'Test Feature Branch'

    env:
      SHA8: ${GITHUB_SHA::8}

    # strategy:
    #   matrix:
    #     stream: [Stream-1, Stream-2, Stream-3, Stream-4]

    steps:
      - uses: actions/checkout@v2
      
      # - name: 'Run Unit Tests'
      #   run: |
      #     export "STREAM=${{ matrix.stream }}"
      #     export "TSTREAM=${STREAM:7}"
      #     echo ${TSTREAM} 
      #     echo ${GITHUB_SHA:0:12}
      #     if [ "$TSTREAM" -eq 4 ]; then export TEST="rule-processing-app/run_tests"; else export TEST="test_stream"; fi
      #     echo ${TEST}
      #     echo "TEST_ENV_NUMBER=$TSTREAM docker-compose run api ./$TEST.sh n$TSTREAM --reporter spec"

      - name: 'Set Env'
        run: echo "SHA8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: 'Create Artifact'
        run:  |
          tar -czf "api-$SHA8.tar.gz" --exclude=.* .
          ls

      - name: 'Save Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: sensibill-api
          path: ./api-$SHA8.tar.gz
          