name: Test & Deploy Feature

on:
  push:
    branches:
      - "ft-*"

jobs:
  test: 
    runs-on: ubuntu-18.04
    name: 'Test Feature Branch'

    env:
      SHA12: $GITHUB_SHA

    strategy:
      matrix:
        stream: [Stream-1, Stream-2, Stream-3]

    steps:
      - name: 'Run Unit Tests'
        run: echo "TEST_ENV_NUMBER=${{ matrix.stream }}:7 docker-compose run api ./test_stream.sh n$TSTREAM --reporter spec"
        env:
          TSTREAM: "$matrix.stream"