name: Feature Branch

# ------------------------------------------------------- #
# Manually trigger this workflow when a pushed feature branch 
# is tagged with this format: deploy-[\d]+ where d can
# signify the deploy number which should be a simple int bunmped up each time
# Eg: deploy-05
# ------------------------------------------------------- #
on:
  push:
    tags:
      - "deploy-G2APIS-*"

jobs:
  test: 
    runs-on: ubuntu-18.04
    name: 'Test Feature Branch'

    steps:

      - uses: actions/checkout@v2

      - run: git --version
      - run: git branch --show-current
      - run: git rev-parse --abbrev-ref HEAD
      
      - run: echo "$GITHUB_REF"
      - run: echo "${GITHUB_REF#refs/*/}"
      - run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: echo "$(git rev-parse tags/deploy-G2APIS-909-12~0)"
      - run: echo "COMMIT=$(git rev-parse tags/deploy-G2APIS-909-12~0)" >> $GITHUB_ENV
      - run: echo "$(git branch -r --contains ${{ github.ref }})"

      - run: echo "$GITHUB_ENV"

      # - run: |
      #     export REMOTE=$(git branch -r --contains ${{ github.ref }})
      #     echo $REMOTE
      #     export BRANCH=${REMOTE/origin\/}
      #     echo $BRANCH

      # - name: Metadata 
      #   run: |
      #     export tag=${GITHUB_REF#refs/*/}
      #     echo "Tag: $tag"
      #     export commit="$(git rev-parse tags/$tag~0)"
      #     echo "Commit: $commit"
      #     export branch="$(git branch -r --contains $commit)"
      #     echo "Branch: $branch"
      #     echo "$branch" >> $GITHUB_ENV
        #  export REMOTE=$(git branch -r --contains ${{ github.ref }})
        #  export BRANCH=${REMOTE/origin\/}
        #  echo "Branch: $BRANCH"
        #  echo $BRANCH >> $GITHUB_ENV

      # - run: echo "$GITHUB_ENV"
      # - run: echo "TAG=${GITHUB_REF#refs/*/}" | tee -a $GITHUB_ENV
      # - run: echo "BRANCH=$(git branch -a --contains ${{ env.TAG }} | grep -v HEAD | cut -d '/' -f3)" | tee -a $GITHUB_ENV


      # - name: Metadata 2
      #   run: |
      #     echo "TAG=${GITHUB_REF#refs/*/}" | tee -a $GITHUB_ENV
      #     echo "BRANCHH=$(git branch -a --contains ${{ env.TAG }} | grep -v HEAD | cut -d '/' -f3)" | tee -a $GITHUB_ENV
      #     echo "${{env.TAG}} - ${{env.BRANCH}}"
          

  deploy: 
    needs: test
    runs-on: ubuntu-18.04
    name: 'Deploy Feature Branch'

    steps:
      - name: Build Artifact
        run: echo "Build Artifact"

      - name: Deploy Artifact
        run: echo "Deploy Artifact"