name: Feature Branch

# ------------------------------------------------------- #
# Manually trigger this workflow when a pushed feature branch 
# is tagged with this format: deploy-[\d]+ where d can
# signify the deploy number which should be a simple int bunmped up each time
# Eg: deploy-05
# ------------------------------------------------------- #
on:
  push:
    tags:
      - "deploy-G2APIS-*"

jobs:
  test: 
    runs-on: ubuntu-18.04
    name: 'Test Feature Branch'

    steps:

      - uses: actions/checkout@v2

      - name: Metadata 
        run: |
         export REMOTE=$(git branch -r --contains ${{ github.ref }})
         export "BRANCH=${REMOTE/origin\/}"
         echo "$BRANCH" >> $GITHUB_ENV

      - run: echo "$GITHUB_ENV"

      - name: GitHub CTX Dump
        env:
          CTX: "${{ toJSON(github) }}"
        run: echo "$CTX"


      # - name: Metadata 2
      #   run: |
      #     echo "TAG=${GITHUB_REF#refs/*/}" | tee -a $GITHUB_ENV
      #     echo "BRANCHH=$(git branch -a --contains ${{ env.TAG }} | grep -v HEAD | cut -d '/' -f3)" | tee -a $GITHUB_ENV
      #     echo "${{env.TAG}} - ${{env.BRANCH}}"
          

  deploy: 
    needs: test
    runs-on: ubuntu-18.04
    name: 'Deploy Feature Branch'

    steps:
      - name: Build Artifact
        run: echo "Build Artifact"

      - name: Deploy Artifact
        run: echo "Deploy Artifact"