name: Test & Deploy Feature

on:
  push:
    branches:
      - "ft-*"

jobs:
  test: 
    runs-on: ubuntu-18.04
    name: 'Test Feature Branch'

    strategy:
      matrix:
        stream: [Stream-1, Stream-2, Stream-3, Stream-4]

    # echo "TEST_ENV_NUMBER=$TSTREAM docker-compose run api ./test_stream.sh n$TSTREAM --reporter spec"
    steps:
      - name: 'Run Unit Tests'
        run: |
          export "STREAM=${{ matrix.stream }}"
          export "TSTREAM=${STREAM:7}"
          echo ${TSTREAM} 
          echo ${GITHUB_SHA:0:12}
          if [ "$TSTREAM" -eq 4 ]; then export TEST="rule-processing-app/run_tests"; else export TEST="test_stream"; fi
          echo ${TEST}
          echo "TEST_ENV_NUMBER=$TSTREAM docker-compose run api ./$TEST.sh n$TSTREAM --reporter spec"
          