name: Feature Branch

# ------------------------------------------------------- #
# Manually trigger this workflow when a pushed feature branch 
# is tagged with this format: deploy-[\d]+ where d can
# signify the deploy number which should be a simple int bunmped up each time
# Eg: deploy-05
# ------------------------------------------------------- #
on:
  push:
    tags:
      - deploy-G2APIS-*

jobs:
  test: 
    runs-on: ubuntu-18.04
    name: 'Test Feature Branch'

    env:
      SHA12: ${GITHUB_SHA:0:12}

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '12.18.3'
      #     cache: 'npm'

      - name: Metadata 1
        run: |
          export "TAG=${GITHUB_REF#refs/*/}"
          export "COMMIT=$(git rev-parse tags/$TAG~0)"
          export "BRANCH=$(git branch --contains $COMMIT)"
          export "BRANCH=${BRANCH:2}"
          echo "Tag: $TAG"
          echo "Commit: $COMMIT"
          echo "Branch: $BRANCH"
          echo "Ref: ${GITHUB_REF}"
          echo "Event: ${GITHUB_EVENT_NAME}"
          echo "SHA12: ${GITHUB_SHA:0:12}"

      - name: Metadata 2
        run: |
          echo "TAGG=${GITHUB_REF#refs/*/}" | tee -a $GITHUB_ENV
          echo "BRANCHH=$(git branch -a --contains ${{ env.TAGG }} | grep -v HEAD | cut -d '/' -f3)" | tee -a $GITHUB_ENV
          echo "${{env.TAGG}} - ${{env.BRANCHH}}"
          

  deploy: 
    needs: test
    runs-on: ubuntu-18.04
    name: 'Deploy Feature Branch'

    steps:
      - name: Build Artifact
        run: echo "Build Artifact"

      - name: Deploy Artifact
        run: echo "Deploy Artifact"