# id : 12145487
name: Integration Tests
on:
  repository_dispatch:
    types: [POSTMAN]
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       description: 'what environment to run the tests on'
  #       required: true
  #       default: 'testing'

jobs:
  newman:
    runs-on: ubuntu-latest
    if: github.event.action == 'POSTMAN' && endsWith(github.ref, '/develop')

    steps:
      # - name: Install Node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'

      # - name: Install Newman
      #   run: npm install -g newman

      # GITHUB_REF / github.ref => refs/heads/<branch_name> | refs/tags/<tag_name>
      - name: Inspect Dispatch/ENV Data
        env:
          REF: "${GITHUB_REF}"
          ACTION: "${{ github.event.action }}"
          TARGET: "${{ github.event.client_payload.environment }}"
        run: |
          echo "Ref: ${GITHUB_REF}"
          echo "Action: ${{ github.event.action }}"
          echo "Test Target: ${{ github.event.client_payload.environment }}"

      # - name: Inspect (Workflow Dispatch)
      #   run: |
      #     echo "ENV => ${{ github.event.inputs.environment }}"
      #     echo "Ref => ${{ github.ref }}"