# id: 12145488

name: GH-A <=> Jenkins

# To trigger this workflow only onMerge, we target the 'closed' activity type of
# a pull_request and conditionally run the job if pull_request.merged is TRUE
# 
# When this happens: 
#   GITHUB_REF => refs/pull/:prNumber/merge
#   GITHUB_SHA => Last merge commit on the GITHUB_REF branch
# 
# See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
# See https://brennerm.github.io/posts/trigger-github-actions-on-pr-close.html
# 
on:
  pull_request:
    types: [closed]

jobs:
  build: 
    runs-on: ubuntu-18.04
    name: 'Fire Jenkins Job'

    # this job will only run when a PR being merged into develop branch
    if: github.event.pull_request.merged == true && github.base_ref == 'develop'

    steps:
      - name: Clone Repo 
        uses: actions/checkout@v2

      - name: Deploy \w Jenkins (fire and forget)
        id: jenkinsRequest
        uses: fjogeleit/http-request-action@master
        with:
          method: 'POST'
          data: '{"branch": "${{ github.base_ref }}", "target": "testing"}'
          url: '${{ secrets.JENKINS_URL }}/generic-webhook-trigger/invoke?token=${{ secrets.GHA_POC_PAT }}'

      - name: Inspect ENVs
        run: echo "Base Branch ${{ github.base_ref }}"